/**
 * Seed a brand-new workspace with the two synthetic sample series so a first-
 * time scorer lands on a populated series list instead of an empty one.
 *
 * Called (best-effort, awaited) from the sign-up hook in `lib/auth.ts` and from
 * `pre-create-user` in `scripts/provision-org.ts`. The data lives in the two
 * `.sailscoring` files next to this module (generated by
 * `scripts/generate-sample-series.ts`); we parse them and replay through the
 * shared `openSeriesFromFile`, which mints fresh ids and writes
 * fleets → competitors → races → starts → finishes.
 *
 * Why a hand-rolled repository adapter instead of `createRepos`: the Postgres
 * repository module is `import 'server-only'`, which throws when imported from
 * the `tsx` CLI (`provision-org`). This adapter writes the same rows directly
 * via Drizzle, so the one seeding path works in the Next server runtime, the
 * CLI, and Vitest alike. The insert shape mirrors `PostgresSeriesRepository`
 * et al.; the schema "mirrors lib/types.ts 1:1", so the mapping is mechanical.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { and, eq, sql } from 'drizzle-orm';

import { getDb, type SailScoringDb } from '@/lib/db/client';
import * as schema from '@/lib/db/schema';
import { FEATURES, type FeatureDef, type FeatureKey } from '@/lib/features';
import { openSeriesFromFile, parseSeriesFile, type SeriesFileRepos } from '@/lib/series-file';
import type { Competitor, Fleet, Race, RaceStart, RaceRatingOverride, Finish, Series, SubSeries } from '@/lib/types';

/**
 * The committed sample data, in the order it appears in the list.
 *
 * Resolved at runtime against `process.cwd()` (the project root in every runtime
 * that reaches here: the Vercel serverless function, the `tsx` provision-org
 * CLI, and Vitest) rather than `new URL('./literal', import.meta.url)`. The
 * module-relative URL form makes Turbopack's file tracer (NFT) walk an `fs` read
 * in the auth route's import graph and conservatively trace the whole project,
 * emitting a warning per reachable route. The files reach the serverless bundle
 * via the explicit `outputFileTracingIncludes` glob in `next.config.ts`, not via
 * the import-graph trace, so cutting that edge is safe.
 */
const SAMPLE_DIR = join(process.cwd(), 'lib', 'sample-series');
const SAMPLE_FILES = ['regatta.sailscoring', 'club-racing.sailscoring'];

/** New workspaces get the samples grouped under this category rather than
 *  scattered through the "Uncategorized" bucket. */
const SAMPLES_CATEGORY_NAME = 'Samples';

/** A Drizzle-backed `SeriesFileRepos` scoped to one workspace. Only the methods
 *  `openSeriesFromFile` calls are implemented; the rest throw if reached. */
function seedRepos(db: SailScoringDb, workspaceId: string): SeriesFileRepos {
  const nextDisplayOrder = sql<number>`(select coalesce(max(${schema.series.displayOrder}) + 1, 0) from ${schema.series} where ${schema.series.workspaceId} = ${workspaceId})`;

  return {
    seriesRepo: {
      get: async () => undefined,
      async save(s: Series) {
        await db.insert(schema.series).values({
          id: s.id,
          workspaceId,
          name: s.name,
          venue: s.venue,
          startDate: s.startDate,
          endDate: s.endDate,
          venueLogoUrl: s.venueLogoUrl,
          eventLogoUrl: s.eventLogoUrl,
          venueUrl: s.venueUrl,
          eventUrl: s.eventUrl,
          createdAt: new Date(s.createdAt),
          lastSavedAt: s.lastSavedAt != null ? new Date(s.lastSavedAt) : null,
          lastModifiedAt: new Date(s.lastModifiedAt),
          scoringMode: s.scoringMode,
          defaultStartSequence: s.defaultStartSequence ?? null,
          discardThresholds: s.discardThresholds,
          dnfScoring: s.dnfScoring,
          ftpHost: s.ftpHost,
          ftpPath: s.ftpPath,
          ftpPaths: s.ftpPaths,
          includeJsonExport: s.includeJsonExport,
          publishRatingCalculations: s.publishRatingCalculations ?? true,
          showPerRaceRatingsInSummary: s.showPerRaceRatingsInSummary ?? true,
          enabledCompetitorFields: s.enabledCompetitorFields,
          primaryPersonLabel: s.primaryPersonLabel,
          subdivisionAxes: s.subdivisionAxes ?? [],
          categoryId: s.categoryId ?? null,
          archived: s.archived ?? false,
          source: s.source ?? null,
          displayOrder: nextDisplayOrder,
        });
        return s;
      },
    } as unknown as SeriesFileRepos['seriesRepo'],

    fleetRepo: {
      async saveMany(fleets: Fleet[]) {
        if (fleets.length === 0) return;
        await db.insert(schema.fleets).values(
          fleets.map((f) => ({
            id: f.id,
            seriesId: f.seriesId,
            workspaceId,
            name: f.name,
            displayOrder: f.displayOrder,
            scoringSystem: f.scoringSystem,
            echoAlpha: f.echoAlpha ?? null,
            nhcProfile: f.nhcProfile ?? null,
          })),
        );
      },
    } as unknown as SeriesFileRepos['fleetRepo'],

    competitorRepo: {
      async saveMany(competitors: Competitor[]) {
        if (competitors.length === 0) return;
        await db.insert(schema.competitors).values(
          competitors.map((c) => ({
            id: c.id,
            seriesId: c.seriesId,
            workspaceId,
            fleetIds: c.fleetIds,
            sailNumber: c.sailNumber,
            boatName: c.boatName ?? null,
            boatClass: c.boatClass ?? null,
            names: c.names,
            owners: c.owners?.length ? c.owners : null,
            helms: c.helms?.length ? c.helms : null,
            crewNames: c.crewNames?.length ? c.crewNames : null,
            club: c.club,
            nationality: c.nationality ?? null,
            gender: c.gender,
            age: c.age,
            subdivisions: c.subdivisions ?? null,
            createdAt: new Date(c.createdAt),
            ircTcc: c.ircTcc ?? null,
            pyNumber: c.pyNumber ?? null,
            nhcStartingTcf: c.nhcStartingTcf ?? null,
            echoStartingTcf: c.echoStartingTcf ?? null,
          })),
        );
      },
    } as unknown as SeriesFileRepos['competitorRepo'],

    raceRepo: {
      async save(r: Race) {
        await db.insert(schema.races).values({
          id: r.id,
          seriesId: r.seriesId,
          workspaceId,
          raceNumber: r.raceNumber,
          date: r.date,
          createdAt: new Date(r.createdAt),
        });
        return r;
      },
    } as unknown as SeriesFileRepos['raceRepo'],

    subSeriesRepo: {
      // Mirrors PostgresSubSeriesRepository.save: upsert the row (so
      // openSeriesFromFile's two-pass 'continue' write patches
      // continueFromSubSeriesId rather than colliding on the PK) and replace
      // membership, carrying per-fleet exclusions on the join row's
      // excludedFleetIds. fleetIds / excludeDncOnlyCompetitors are scoping the
      // scoring engine reads, so they must round-trip too.
      async saveMany(list: SubSeries[]) {
        if (list.length === 0) return;
        for (const ss of list) {
          const row = {
            id: ss.id,
            seriesId: ss.seriesId,
            workspaceId,
            name: ss.name,
            displayOrder: ss.displayOrder,
            fleetIds: ss.fleetIds ?? null,
            startingHandicapSource: ss.startingHandicapSource ?? 'base',
            continueFromSubSeriesId: ss.continueFromSubSeriesId ?? null,
            excludeDncOnlyCompetitors: ss.excludeDncOnlyCompetitors ?? false,
          };
          await db
            .insert(schema.subSeries)
            .values(row)
            .onConflictDoUpdate({ target: schema.subSeries.id, set: row });

          // Replace membership: delete then re-insert, so a second saveMany for
          // the same sub-series (the continueFrom pass) doesn't duplicate rows.
          await db
            .delete(schema.subSeriesRaces)
            .where(eq(schema.subSeriesRaces.subSeriesId, ss.id));
          const excludedByRace = new Map<string, string[]>();
          for (const ex of ss.raceFleetExclusions ?? []) {
            const fleets = excludedByRace.get(ex.raceId) ?? [];
            fleets.push(ex.fleetId);
            excludedByRace.set(ex.raceId, fleets);
          }
          if (ss.raceIds.length > 0) {
            await db.insert(schema.subSeriesRaces).values(
              ss.raceIds.map((raceId) => ({
                subSeriesId: ss.id,
                raceId,
                workspaceId,
                excludedFleetIds: excludedByRace.get(raceId) ?? [],
              })),
            );
          }
        }
      },
    } as unknown as SeriesFileRepos['subSeriesRepo'],

    raceStartRepo: {
      async saveMany(starts: RaceStart[]) {
        if (starts.length === 0) return;
        await db.insert(schema.raceStarts).values(
          starts.map((s) => ({
            id: s.id,
            raceId: s.raceId,
            fleetIds: s.fleetIds,
            startTime: s.startTime,
          })),
        );
      },
    } as unknown as SeriesFileRepos['raceStartRepo'],

    raceRatingOverrideRepo: {
      async saveMany(overrides: RaceRatingOverride[]) {
        if (overrides.length === 0) return;
        await db.insert(schema.raceRatingOverrides).values(
          overrides.map((o) => ({
            id: o.id,
            raceId: o.raceId,
            competitorId: o.competitorId,
            field: o.field,
            value: o.value,
          })),
        );
      },
    } as unknown as SeriesFileRepos['raceRatingOverrideRepo'],

    finishRepo: {
      async saveMany(finishes: Finish[]) {
        if (finishes.length === 0) return;
        await db.insert(schema.finishes).values(
          finishes.map((f) => ({
            id: f.id,
            raceId: f.raceId,
            competitorId: f.competitorId,
            unknownSailNumber: f.unknownSailNumber ?? null,
            sortOrder: f.sortOrder,
            tiedWithPrevious: f.tiedWithPrevious,
            finishTime: f.finishTime ?? null,
            resultCode: f.resultCode,
            startPresent: f.startPresent,
            penaltyCode: f.penaltyCode,
            penaltyOverride: f.penaltyOverride,
            redressMethod: f.redressMethod,
            redressExcludeRaceIds: f.redressExcludeRaceIds,
            redressIncludeRaceIds: f.redressIncludeRaceIds,
            redressIncludeAllLater: f.redressIncludeAllLater,
            redressPoints: f.redressPoints,
          })),
        );
      },
    } as unknown as SeriesFileRepos['finishRepo'],

    async listSeriesNames() {
      const rows = await db
        .select({ name: schema.series.name })
        .from(schema.series)
        .where(eq(schema.series.workspaceId, workspaceId));
      return rows.map((r) => r.name);
    },
    deleteSeriesChildren: async () => {
      throw new Error('seedSampleSeries never deletes — it only writes fresh series');
    },
  };
}

/** The id of this workspace's "Samples" category, creating it (appended after
 *  any existing categories) if it doesn't exist yet. Shared by the sign-up
 *  seeding and the on-enable feature-demo seeding, so both land in one place. */
async function ensureSamplesCategory(
  db: SailScoringDb,
  workspaceId: string,
): Promise<string> {
  const [existing] = await db
    .select({ id: schema.categories.id })
    .from(schema.categories)
    .where(
      and(
        eq(schema.categories.workspaceId, workspaceId),
        eq(schema.categories.name, SAMPLES_CATEGORY_NAME),
      ),
    )
    .limit(1);
  if (existing) return existing.id;
  const categoryId = crypto.randomUUID();
  await db.insert(schema.categories).values({
    id: categoryId,
    workspaceId,
    name: SAMPLES_CATEGORY_NAME,
    displayOrder: sql<number>`(select coalesce(max(${schema.categories.displayOrder}) + 1, 0) from ${schema.categories} where ${schema.categories.workspaceId} = ${workspaceId})`,
  });
  return categoryId;
}

/**
 * Seed both sample series into `workspaceId`. Atomic per call (one transaction)
 * so a mid-seed failure leaves no half-written series. Callers run this
 * best-effort: a failure must never block account creation.
 */
export async function seedSampleSeries(
  workspaceId: string,
  db: SailScoringDb = getDb(),
): Promise<void> {
  await db.transaction(async (tx) => {
    const txDb = tx as unknown as SailScoringDb;
    // Group both samples under a "Samples" category. `categoryId` is
    // workspace-local (not carried in the .sailscoring file), so we create the
    // category here and pass its id to openSeriesFromFile.
    const categoryId = await ensureSamplesCategory(txDb, workspaceId);
    const repos = seedRepos(txDb, workspaceId);
    for (const name of SAMPLE_FILES) {
      const file = parseSeriesFile(readFileSync(join(SAMPLE_DIR, name), 'utf8'));
      await openSeriesFromFile(file, repos, { categoryId });
    }
  });
}

/**
 * Seed a feature's worked example (`FeatureDef.demoSample`) into `workspaceId`,
 * grouped under the same "Samples" category as the sign-up seeds. Called when a
 * feature is switched on for the first time (see `setWorkspaceFeature`), so the
 * scorer meets a live, editable demonstration rather than an empty affordance.
 *
 * Returns whether a demo was seeded — `false` when the feature has no
 * `demoSample`, so the caller can skip recording the one-time marker. Atomic
 * per call and run best-effort by the caller: a failure must never fail the
 * toggle itself.
 */
export async function seedFeatureSample(
  feature: FeatureKey,
  workspaceId: string,
  db: SailScoringDb = getDb(),
): Promise<boolean> {
  const fileName = (FEATURES[feature] as FeatureDef).demoSample;
  if (!fileName) return false;
  await db.transaction(async (tx) => {
    const txDb = tx as unknown as SailScoringDb;
    const categoryId = await ensureSamplesCategory(txDb, workspaceId);
    const repos = seedRepos(txDb, workspaceId);
    const file = parseSeriesFile(readFileSync(join(SAMPLE_DIR, fileName), 'utf8'));
    await openSeriesFromFile(file, repos, { categoryId });
  });
  return true;
}
