/**
 * Sailwave 2.38.02 boilerplate for the .blw exporter — the series-level
 * defaults, the root scoring system, its scoring codes and the column
 * definitions a freshly created Sailwave file carries. Captured verbatim from
 * a real 2.38.02 file (custom column titles cleared, file-specific globals
 * dropped). Regenerate with the generator script when the target Sailwave
 * version moves.
 *
 * In the code rows '@' stands for the root scoring-system handle.
 */
export const SAILWAVE_TEMPLATE_VERSION = '2.38.02';

export const SAILWAVE_GLOBAL_DEFAULTS: ReadonlyArray<readonly [string, string]> = [
  ["serallowfixedflights", "0"],
  ["sersocial", "0"],
  ["serisafpub", "1"],
  ["serflagspub", "0"],
  ["serflagstext", "0"],
  ["serhidediscards", "0"],
  ["sernodiscardformat", "0"],
  ["serhidefields", "0"],
  ["sersep", "0"],
  ["serseprow", "0"],
  ["serpubpbreak", "0"],
  ["serpubfirstn", "0"],
  ["serpubincludecodes", "0"],
  ["serpubincludecontents", "0"],
  ["serincludelaps", "0"],
  ["serincludestarttimes", "0"],
  ["serincludefinishtimes", "0"],
  ["serincludecorrected", "1"],
  ["serincludedncs", "0"],
  ["serincludespeed", "0"],
  ["serincludeewin", "0"],
  ["serincluderwin", "0"],
  ["serpubwhere", "sailwave"],
  ["serpubincluderaces", "2"],
  ["serpubincluderaces2", "2"],
  ["serpubincludenotes", "0"],
  ["serpubincludeseries", "1"],
  ["serpubincludeprizes", "0"],
  ["serpubincludedates", "1"],
  ["serpubincludetimes", "0"],
  ["serpubstartcols", "0"],
  ["serhidepropbar", "0"],
  ["serpropbarwidth", "171"],
  ["serpropbartree", "0"],
  ["serhideexcluded", "0"],
  ["serhideunsailed", "0"],
  ["servenuewebsite", "www.skerriessailingclub.com/"],
  ["serpoponoffcolumns", "Race, Sign On, Sign Off"],
  ["serentrycolumns", "Extra Col 1,Extra Col 2"],
  ["serdecalttitle", "Declaration of Alternative Penalties"],
  ["serdecaltcolumns", "Date, Race, Class/SailNo, Description of Incident, Alternative Penalty (e.g. 720),Initials"],
  ["serdecaltrows", "25"],
  ["sernoticetitle", "Competitor Notice"],
  ["seronofftitle", "Sign On/Off Declaration"],
  ["seronoffcolumns", "Date, Race, Class/SailNo, Sign On, Sign Off"],
  ["seronoffrows", "25"],
  ["serdecrettitle", "Declaration of Retirements"],
  ["serdecretcolumns", "Date, Race, Class/SailNo, Ret Code, Initials"],
  ["serdecretrows", "25"],
  ["serpubincluderacetables", "1"],
  ["serpubflightrace", "1"],
  ["sersortcol", "4"],
  ["sersortcol2", "2"],
  ["sersortdir", "1"],
  ["sersortdir2", "1"],
  ["serlistface", "Arial"],
  ["serlistsize", "10"],
  ["serlistcolour", "0"],
  ["serelapsedview", "3"],
];

/** Root scoring-system rows. Discard list, rating system and DNC/DNF bases are
 *  overridden by the exporter. */
export const SAILWAVE_SCORING_SYSTEM_DEFAULTS: ReadonlyArray<readonly [string, string]> = [
  ["scrfollowchamp", "0"],
  ["scrfollowmedal", "0"],
  ["scrfollowcodes", "0"],
  ["scrfollowratingsystem", "0"],
  ["scrfollowratingmode", "0"],
  ["scrfollowpointssystem", "0"],
  ["scrfollowcoefficients", "0"],
  ["scrfollowcustomexprs", "0"],
  ["scrfollowseriesties", "0"],
  ["scrfollowoverallpoints", "0"],
  ["scrfollowdiscards", "0"],
  ["scrfollowraceties", "0"],
  ["scrfollowflights", "0"],
  ["scrfollowpointsplaces", "0"],
  ["scrfollowqualification", "0"],
  ["scrhotkey", "0"],
  ["scrname", "Appendix A"],
  ["scrparent", "0"],
  ["scrfield", "Fleet"],
  ["scrfield2", "Fleet"],
  ["scrsfield", "Fleet"],
  ["scrsfield2", "Fleet"],
  ["scrtie3", "No"],
  ["scrtie0", "No"],
  ["scrtie1", "Yes"],
  ["scrincludediscards", "No"],
  ["scrtie2", "Yes"],
  ["scrtie2back", "No"],
  ["scrtie2starts", "No"],
  ["scrtiefinals", "No"],
  ["scrraceties", "Averaged"],
  ["scrpointsplaces", "1"],
  ["scrrrs2025", "Yes"],
  ["scrpointsaccumulation", "Sum"],
  ["scrpointssystem", "Low point"],
  ["scrratingsystem", "PY"],
  ["scrratingvalue", "No"],
  ["scrwindstrengths", "0-1,2-3,4,5-9"],
  ["scrupdateratings", "No"],
  ["scrbackcalcpercent", "0"],
  ["scrdiscardlist", "0,0,0,1,1,1"],
  ["scrflights", "No"],
  ["scrfinals", "No"],
  ["scrfinalsstickyq", "No"],
  ["scrfinalsfirst", "0"],
  ["scrlowweight", "Yes"],
  ["scrmedal", "No"],
  ["scrmedalrace", "3"],
  ["scrmedalyesnotdiscardable", "Yes"],
  ["scrmedalyesmultiply", "Yes"],
  ["scrmedalyestie", "Yes"],
  ["scrmedalnonotdiscardable", "Yes"],
  ["scrmedalnomultiply", "Yes"],
  ["scrmedalnotie", "Yes"],
  ["scrmedalmax", "10"],
];

/** Scoring-code rows for the root system: pipe-delimited
 *  `code|method|value|...|systemHandle(idx 14)|...|description`. */
export const SAILWAVE_SCORING_CODE_DEFAULTS: ReadonlyArray<string> = [
  "BFD|Score like|DNF|Yes|Yes|||spare|spare|spare|spare|No|No|No|@||Black flag disqualification under rule 30.4",
  "DGM|Score like|DSQ|No|Yes|||spare|spare|spare|spare|Yes|Yes|No|@||Disqualification not excludable under rule 69.1(b)(2)",
  "DNC|Finishers +|2|Yes|No|||spare|spare|spare|spare|No|No|No|@||Did not come to the starting area",
  "DNE|Score like|DSQ|No|Yes|||spare|spare|spare|spare|Yes|Yes|No|@||Disqualification (other then DGM) not excludable under rule 90.3(b)",
  "DNF|Finishers +|1|Yes|Yes|||spare|spare|spare|spare|Yes|No|No|@||Started but did not finish",
  "DNS|Score like|DNF|Yes|Yes|||spare|spare|spare|spare|No|No|No|@||Came to the start area but did not start",
  "DPI1|Fixed penalty|1|Yes|Yes|||spare|spare|spare|spare|Yes|Yes|Yes|@||1 point discretionary penalty",
  "DSQ|Score like|DNF|Yes|Yes|||spare|spare|spare|spare|Yes|Yes|No|@||Disqualification",
  "NSC|Score like|DNF|Yes|Yes|||spare|spare|spare|spare|Yes|No|No|@||A boat did not sail the course as defined rule A5.1",
  "OCS|Score like|DNF|Yes|Yes|||spare|spare|spare|spare|No|No|No|@||On course side at start or broke rule 30.1",
  "OOD|Average (all)||Yes|No|||spare|spare|spare|spare|Yes|Yes|No|@||Race officer duty points scored as RDGa",
  "RDG|Set points by hand||Yes|Yes|||spare|spare|spare|spare|Yes|Yes|Yes|@||Redress - points set by protest hearing",
  "RDGa|Average (all)||Yes|Yes|||spare|spare|spare|spare|Yes|Yes|Yes|@||Redress - average points for all races except the race in question",
  "RDGb|Average (before)||Yes|Yes|||spare|spare|spare|spare|Yes|Yes|Yes|@||Redress - average points for all races preceeding the race in question",
  "RET|Score like|DNF|Yes|Yes|||spare|spare|spare|spare|Yes|No|No|@||Retired",
  "SCP|Percentage penalty DNF|20|Yes|Yes|||spare|spare|spare|spare|Yes|Yes|Yes|@||Scoring penalty under rule 44.3",
  "UFD|Score like|DNF|Yes|Yes|||spare|spare|spare|spare|No|No|No|@||U flag disqualification under rule 30.3",
  "ZFP|Percentage penalty DNF|20|Yes|Yes|||spare|spare|spare|spare|Yes|Yes|Yes|@||20% penalty under rule 30.2",
];

/** Column definitions: `enabled|FieldName|fieldId|showInGrid|publish|width|title|`. */
export const SAILWAVE_COLUMN_DEFAULTS: ReadonlyArray<string> = [
  "1|AltSailNo|17|No|No|40||",
  "1|Boat|16|No|No|40||",
  "1|BowNumber|15|No|No|40||",
  "1|CarriedFwd|43|No|No|20||",
  "1|Class|7|Yes|Yes|55||",
  "1|Club|10|Yes|Yes|139||",
  "1|CrewAddress|38|No|No|40||",
  "1|CrewAgeGroup|31|No|No|40||",
  "1|CrewEmail|32|No|No|40||",
  "1|CrewId|30|No|No|81||",
  "1|CrewMemberNo|35|No|No|40||",
  "1|CrewName|18|No|No|40||",
  "1|CrewNotes|39|No|No|40||",
  "1|CrewPhone|36|No|No|40||",
  "1|CrewPhoto|37|No|No|40||",
  "1|CrewSex|34|No|No|40||",
  "1|CrewWebsite|33|No|No|40||",
  "1|Division|6|Yes|No|51||",
  "1|Exclude|2|Yes|No|10||",
  "1|Fee|41|No|No|40||",
  "1|Fleet|5|Yes|Yes|53||",
  "1|HelmAddress|28|No|No|40||",
  "1|HelmAgeGroup|22|No|No|40||",
  "1|HelmEmail|23|No|No|40||",
  "1|HelmId|21|No|No|40||",
  "1|HelmMemberNo|25|No|No|40||",
  "1|HelmName|9|Yes|Yes|136||",
  "1|HelmNotes|29|No|No|40||",
  "1|HelmPhone|26|No|No|40||",
  "1|HelmPhoto|27|No|No|40||",
  "1|HelmSex|11|Yes|No|40||",
  "1|HelmWebsite|24|No|No|40||",
  "1|Medical|14|No|No|40||",
  "1|MedicalFlag|1|No|No|10||",
  "1|Nat|13|No|No|40||",
  "1|Nett|46|Yes|Yes|43||",
  "1|NewRating|20|No|No|40||",
  "1|Notes|47|No|No|40||",
  "1|Paid|42|No|No|40||",
  "1|Penalties|44|No|No|20||",
  "1|PrivateNotes|48|No|No|40||",
  "1|Rank|3|Yes|Yes|40||",
  "1|Rating|19|No|No|40||",
  "1|SailNo|8|Yes|Yes|35||",
  "1|Status|40|No|No|40||",
  "1|Tally|4|Yes|No|27||",
  "1|Total|45|Yes|Yes|43||",
  "2||12|Yes|Yes|42||",
  "3||1000|Yes|No|40||",
  "1|Alias|12|Yes|No|10||",
  "1|Flight|36|No|No|40||",
  "1|Seeding|50|No|No|40||",
  "1|WindRats|52|No|No|40||",
  "1|Formula|53|No|No|40||",
  "1|Platform|54|No|No|40||",
  "1|Rig|55|No|No|40||",
  "1|Sailmaker|56|No|No|40||",
  "1|Foils|57|No|No|40||",
  "1|SkipperName|58|No|No|40||",
  "1|SkipperId|59|No|No|40||",
  "1|SkipperAgeGroup|60|No|No|40||",
  "1|SkipperEmail|61|No|No|40||",
  "1|SkipperWebsite|62|No|No|40||",
  "1|SkipperSex|63|No|No|40||",
  "1|SkipperMemberNo|64|No|No|40||",
  "1|SkipperPhone|65|No|No|40||",
  "1|SkipperPhoto|66|No|No|40||",
  "1|SkipperAddress|67|No|No|40||",
  "1|SkipperNotes|68|No|No|40||",
  "1|TacticianName|69|No|No|40||",
  "1|TacticianId|70|No|No|40||",
  "1|TacticianAgeGroup|71|No|No|40||",
  "1|TacticianEmail|72|No|No|40||",
  "1|TacticianWebsite|73|No|No|40||",
  "1|TacticianSex|74|No|No|40||",
  "1|TacticianMemberNo|75|No|No|40||",
  "1|TacticianPhone|76|No|No|40||",
  "1|TacticianPhoto|77|No|No|40||",
  "1|TacticianAddress|78|No|No|40||",
  "1|TacticianNotes|79|No|No|40||",
  "1|NavigatorName|80|No|No|40||",
  "1|NavigatorId|81|No|No|40||",
  "1|NavigatorAgeGroup|82|No|No|40||",
  "1|NavigatorEmail|83|No|No|40||",
  "1|NavigatorWebsite|84|No|No|40||",
  "1|NavigatorSex|85|No|No|40||",
  "1|NavigatorMemberNo|86|No|No|40||",
  "1|NavigatorPhone|87|No|No|40||",
  "1|NavigatorPhoto|88|No|No|40||",
  "1|NavigatorAddress|89|No|No|40||",
  "1|NavigatorNotes|90|No|No|40||",
  "1|BowmanName|91|No|No|40||",
  "1|BowmanId|92|No|No|40||",
  "1|BowmanAgeGroup|93|No|No|40||",
  "1|BowmanEmail|94|No|No|40||",
  "1|BowmanWebsite|95|No|No|40||",
  "1|BowmanSex|96|No|No|40||",
  "1|BowmanMemberNo|97|No|No|40||",
  "1|BowmanPhone|98|No|No|40||",
  "1|BowmanPhoto|99|No|No|40||",
  "1|BowmanAddress|100|No|No|40||",
  "1|BowmanNotes|101|No|No|40||",
  "1|MastName|102|No|No|40||",
  "1|MastId|103|No|No|40||",
  "1|MastAgeGroup|104|No|No|40||",
  "1|MastEmail|105|No|No|40||",
  "1|MastWebsite|106|No|No|40||",
  "1|MastSex|107|No|No|40||",
  "1|MastMemberNo|108|No|No|40||",
  "1|MastPhone|109|No|No|40||",
  "1|MastPhoto|110|No|No|40||",
  "1|MastAddress|111|No|No|40||",
  "1|MastNotes|112|No|No|40||",
  "1|PitName|113|No|No|40||",
  "1|PitId|114|No|No|40||",
  "1|PitAgeGroup|115|No|No|40||",
  "1|PitEmail|116|No|No|40||",
  "1|PitWebsite|117|No|No|40||",
  "1|PitSex|118|No|No|40||",
  "1|PitMemberNo|119|No|No|40||",
  "1|PitPhone|120|No|No|40||",
  "1|PitPhoto|121|No|No|40||",
  "1|PitAddress|122|No|No|40||",
  "1|PitNotes|123|No|No|40||",
  "1|MaintrimName|124|No|No|40||",
  "1|MaintrimId|125|No|No|40||",
  "1|MaintrimAgeGroup|126|No|No|40||",
  "1|MaintrimEmail|127|No|No|40||",
  "1|MaintrimWebsite|128|No|No|40||",
  "1|MaintrimSex|129|No|No|40||",
  "1|MaintrimMemberNo|130|No|No|40||",
  "1|MaintrimPhone|131|No|No|40||",
  "1|MaintrimPhoto|132|No|No|40||",
  "1|MaintrimAddress|133|No|No|40||",
  "1|MaintrimNotes|134|No|No|40||",
  "1|PorttrimName|135|No|No|40||",
  "1|PorttrimId|136|No|No|40||",
  "1|PorttrimAgeGroup|137|No|No|40||",
  "1|PorttrimEmail|138|No|No|40||",
  "1|PorttrimWebsite|139|No|No|40||",
  "1|PorttrimSex|140|No|No|40||",
  "1|PorttrimMemberNo|141|No|No|40||",
  "1|PorttrimPhone|142|No|No|40||",
  "1|PorttrimPhoto|143|No|No|40||",
  "1|PorttrimAddress|144|No|No|40||",
  "1|PorttrimNotes|145|No|No|40||",
  "1|StartrimName|146|No|No|40||",
  "1|StartrimId|147|No|No|40||",
  "1|StartrimAgeGroup|148|No|No|40||",
  "1|StartrimEmail|149|No|No|40||",
  "1|StartrimWebsite|150|No|No|40||",
  "1|StartrimSex|151|No|No|40||",
  "1|StartrimMemberNo|152|No|No|40||",
  "1|StartrimPhone|153|No|No|40||",
  "1|StartrimPhoto|154|No|No|40||",
  "1|StartrimAddress|155|No|No|40||",
  "1|StartrimNotes|156|No|No|40||",
  "1|PortgrindName|157|No|No|40||",
  "1|PortgrindId|158|No|No|40||",
  "1|PortgrindAgeGroup|159|No|No|40||",
  "1|PortgrindEmail|160|No|No|40||",
  "1|PortgrindWebsite|161|No|No|40||",
  "1|PortgrindSex|162|No|No|40||",
  "1|PortgrindMemberNo|163|No|No|40||",
  "1|PortgrindPhone|164|No|No|40||",
  "1|PortgrindPhoto|165|No|No|40||",
  "1|PortgrindAddress|166|No|No|40||",
  "1|PortgrindNotes|167|No|No|40||",
  "1|StargrindName|168|No|No|40||",
  "1|StargrindId|169|No|No|40||",
  "1|StargrindAgeGroup|170|No|No|40||",
  "1|StargrindEmail|171|No|No|40||",
  "1|StargrindWebsite|172|No|No|40||",
  "1|StargrindSex|173|No|No|40||",
  "1|StargrindMemberNo|174|No|No|40||",
  "1|StargrindPhone|175|No|No|40||",
  "1|StargrindPhoto|176|No|No|40||",
  "1|StargrindAddress|177|No|No|40||",
  "1|StargrindNotes|178|No|No|40||",
  "1|OwnerName|179|No|No|40||",
  "1|OwnerId|180|No|No|40||",
  "1|OwnerAgeGroup|181|No|No|40||",
  "1|OwnerEmail|182|No|No|40||",
  "1|OwnerWebsite|183|No|No|40||",
  "1|OwnerSex|184|No|No|40||",
  "1|OwnerMemberNo|185|No|No|40||",
  "1|OwnerPhone|186|No|No|40||",
  "1|OwnerPhoto|187|No|No|40||",
  "1|OwnerAddress|188|No|No|40||",
  "1|OwnerNotes|189|No|No|40||",
  "1|GuestName|190|No|No|40||",
  "1|GuestId|191|No|No|40||",
  "1|GuestAgeGroup|192|No|No|40||",
  "1|GuestEmail|193|No|No|40||",
  "1|GuestWebsite|194|No|No|40||",
  "1|GuestSex|195|No|No|40||",
  "1|GuestMemberNo|196|No|No|40||",
  "1|GuestPhone|197|No|No|40||",
  "1|GuestPhoto|198|No|No|40||",
  "1|GuestAddress|199|No|No|40||",
  "1|GuestNotes|200|No|No|40||",
  "1|District|201|No|No|40||",
  "1|Squad|202|No|No|40||",
  "1|Area|203|No|No|40||",
  "1|Region|204|No|No|40||",
  "1|Group|205|No|No|40||",
  "1|Medalist|206|No|No|40||",
  "1|Sponsor|207|No|No|40||",
  "1|SponsorWebsite|208|No|No|40||",
  "1|SponsorEmail|209|No|No|40||",
  "1|Team|210|No|No|40||",
  "1|TeamWebsite|211|No|No|40||",
  "1|TeamEmail|212|No|No|40||",
];
