/**
 * Sync the course-cards data sets into the app.
 *
 * Run: pnpm course-cards:sync   (also run automatically by `prebuild`)
 *
 * The pinned release lives in lib/course-cards/dataset-version.txt. Two
 * outputs, mirroring scripts/sync-canonical-logos.ts:
 *
 *   - lib/course-cards/generated/catalogue.ts — the committed catalogue of
 *     sets and cards (club, event, card ids, counts), typed as the library
 *     reads it, so the picker renders without a network call.
 *   - lib/course-cards/generated/routing.ts — each set's routing overlay,
 *     where it has one, with the positions of the marks its passages turn
 *     at. Committed like the catalogue: a course's legs are worked out
 *     synchronously, in the browser and on the publishing server alike.
 *   - public/course-cards/<set>/<file> — the marks, the card files and each
 *     set's captured chart, gitignored and re-fetched at build time; the app
 *     fetches a card or a chart on demand from its own origin, so there is no
 *     CORS and no runtime dependency on courses.sailscoring.ie.
 *
 * Idempotent: if public/course-cards/.version already matches the pin, the
 * download is skipped so repeat builds are fast and offline-friendly.
 */

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { setTimeout } from 'node:timers/promises';

import {
  parseCatalogue,
  parseCourseCardFile,
  parseMarksFile,
  parseRoutingFile,
  type Catalogue,
  type MarksFile,
  type RoutingFile,
  type Waypoint,
} from '@sailscoring/course-cards';

const LIB_DIR = join(__dirname, '..', 'lib', 'course-cards');
const VERSION_FILE = join(LIB_DIR, 'dataset-version.txt');
const GENERATED_DIR = join(LIB_DIR, 'generated');
const PUBLIC_DIR = join(__dirname, '..', 'public', 'course-cards');
const VERSION_MARKER = join(PUBLIC_DIR, '.version');
const SITE = 'https://courses.sailscoring.ie';

const FETCH_ATTEMPTS = 3;
const RETRY_BASE_MS = 1000;

function isRetriableStatus(status: number): boolean {
  return status === 408 || status === 429 || status >= 500;
}

function errorSummary(err: unknown): string {
  if (!(err instanceof Error)) return String(err);
  return err.cause instanceof Error ? `${err.message} (${err.cause.message})` : err.message;
}

/** Fetch one file of the release, retrying the failures worth retrying. */
async function fetchText(url: string): Promise<string> {
  let lastError: unknown;
  for (let attempt = 1; attempt <= FETCH_ATTEMPTS; attempt++) {
    if (attempt > 1) {
      const delay = RETRY_BASE_MS * 2 ** (attempt - 2);
      console.log(`Retrying ${url} in ${delay}ms (attempt ${attempt}/${FETCH_ATTEMPTS}): ${errorSummary(lastError)}`);
      await setTimeout(delay);
    }
    let res: Response;
    try {
      res = await fetch(url);
    } catch (err) {
      lastError = err;
      continue;
    }
    if (res.ok) return res.text();
    const err = new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
    if (!isRetriableStatus(res.status)) throw err;
    lastError = err;
  }
  throw new Error(`Failed to fetch ${url} after ${FETCH_ATTEMPTS} attempts: ${errorSummary(lastError)}`, {
    cause: lastError,
  });
}

/** Fetch one binary file of the release — a set's chart image — with the
 *  same retries. */
async function fetchBytes(url: string): Promise<Uint8Array> {
  let lastError: unknown;
  for (let attempt = 1; attempt <= FETCH_ATTEMPTS; attempt++) {
    if (attempt > 1) {
      const delay = RETRY_BASE_MS * 2 ** (attempt - 2);
      console.log(`Retrying ${url} in ${delay}ms (attempt ${attempt}/${FETCH_ATTEMPTS}): ${errorSummary(lastError)}`);
      await setTimeout(delay);
    }
    let res: Response;
    try {
      res = await fetch(url);
    } catch (err) {
      lastError = err;
      continue;
    }
    if (res.ok) return new Uint8Array(await res.arrayBuffer());
    const err = new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
    if (!isRetriableStatus(res.status)) throw err;
    lastError = err;
  }
  throw new Error(`Failed to fetch ${url} after ${FETCH_ATTEMPTS} attempts: ${errorSummary(lastError)}`, {
    cause: lastError,
  });
}

/**
 * Parse one fetched file, naming it when the library refuses it: the parser's
 * own message says what is wrong ("card.courses: expected courses") but not
 * in which of the release's files, which is what a failed build needs.
 */
function checked<T>(url: string, text: string, parse: (data: unknown) => T): T {
  try {
    return parse(JSON.parse(text));
  } catch (err) {
    throw new Error(`${url}: ${errorSummary(err)}`, { cause: err });
  }
}

function renderCatalogueModule(catalogue: Catalogue): string {
  return [
    '// AUTOGENERATED by scripts/sync-course-cards.ts — do not edit by hand.',
    `// Source: ${SITE}/v${catalogue.version}/index.json`,
    '',
    "import type { Catalogue } from '@sailscoring/course-cards';",
    '',
    `export const COURSE_CARDS_RELEASE = ${JSON.stringify(catalogue.version)};`,
    '',
    `export const COURSE_CARD_CATALOGUE: Catalogue = ${JSON.stringify(catalogue, null, 2)};`,
    '',
  ].join('\n');
}

/**
 * The marks a set's passages turn at, where its marks file places them: a
 * passage from Ringabella to Cage goes by W2, and a course that never rounds
 * W2 still has to know where it is. Taken from the same release as the
 * overlay, so a snapshot that never held W2 routes the way its course did.
 */
function turnMarks(routing: RoutingFile, marks: MarksFile): Waypoint[] {
  const waypointIds = new Set(routing.waypoints.map((w) => w.id));
  const assumed = new Map(routing.assumed.map((a) => [a.id, a]));
  const ids = new Set<string>();
  for (const p of routing.passages) {
    for (const v of p.via) if (!waypointIds.has(v) && assumed.has(v)) ids.add(assumed.get(v)!.mark);
  }
  return marks.marks
    .filter((m) => ids.has(m.id) && m.position)
    .map((m) => ({ mark: m.id, label: m.id, position: m.position!, ...(marks.source ? { source: marks.source } : {}) }));
}

function renderRoutingModule(version: string, overlays: Record<string, { routing: RoutingFile; turnAt: Waypoint[] }>): string {
  return [
    '// AUTOGENERATED by scripts/sync-course-cards.ts — do not edit by hand.',
    `// Source: ${SITE}/v${version}/<set>/routing.json and its marks file`,
    '',
    "import type { RoutingFile, Waypoint } from '@sailscoring/course-cards';",
    '',
    `export const COURSE_ROUTING: Record<string, { routing: RoutingFile; turnAt: Waypoint[] }> = ${JSON.stringify(overlays, null, 2)};`,
    '',
  ].join('\n');
}

async function main() {
  const version = readFileSync(VERSION_FILE, 'utf8').trim();
  if (!/^\d+\.\d+\.\d+$/.test(version)) {
    throw new Error(`dataset-version.txt must contain MAJOR.MINOR.PATCH, got ${JSON.stringify(version)}`);
  }

  const haveCatalogue = existsSync(join(GENERATED_DIR, 'catalogue.ts')) && existsSync(join(GENERATED_DIR, 'routing.ts'));
  const haveFiles = existsSync(VERSION_MARKER) && readFileSync(VERSION_MARKER, 'utf8').trim() === version;
  if (haveCatalogue && haveFiles) {
    console.log(`course-cards ${version} already in sync — skipping.`);
    return;
  }

  console.log(`Syncing course-cards ${version}…`);
  const catalogue = parseCatalogue(JSON.parse(await fetchText(`${SITE}/v${version}/index.json`)));
  if (catalogue.version !== version) {
    throw new Error(`catalogue says version ${catalogue.version}, pin says ${version}`);
  }

  rmSync(PUBLIC_DIR, { recursive: true, force: true });
  mkdirSync(PUBLIC_DIR, { recursive: true });
  let files = 0;
  const overlays: Record<string, { routing: RoutingFile; turnAt: Waypoint[] }> = {};
  for (const set of catalogue.sets) {
    // Every file is parsed before it is written: a card the library refuses
    // is a release problem to fail the build on, not one to ship.
    const marksText = await fetchText(set.marks.url);
    const marks = checked(set.marks.url, marksText, parseMarksFile);
    const marksPath = join(PUBLIC_DIR, set.marks.file);
    mkdirSync(dirname(marksPath), { recursive: true });
    writeFileSync(marksPath, marksText);
    files += 1;
    for (const card of set.cards) {
      const cardText = await fetchText(card.url);
      checked(card.url, cardText, parseCourseCardFile);
      const cardPath = join(PUBLIC_DIR, card.json);
      mkdirSync(dirname(cardPath), { recursive: true });
      writeFileSync(cardPath, cardText);
      files += 1;
    }
    // The set's routing overlay: which legs the straight line will do, and
    // the passages round the ones it won't.
    if (set.routing) {
      const routing = checked(set.routing.url, await fetchText(set.routing.url), parseRoutingFile);
      overlays[set.path] = { routing, turnAt: turnMarks(routing, marks) };
    }
    // The set's captured chart: the ground a course is drawn on. Everything
    // the renderer has to know about the image — what it covers, how big it
    // is, who to attribute — travels in the catalogue, so only the image
    // itself is fetched. Sets without one draw on plain ground.
    if (set.map?.placement) {
      const png = await fetchBytes(`${SITE}/v${version}/${set.map.background}`);
      const pngPath = join(PUBLIC_DIR, set.map.background);
      mkdirSync(dirname(pngPath), { recursive: true });
      writeFileSync(pngPath, png);
      files += 1;
    }
  }
  writeFileSync(VERSION_MARKER, `${version}\n`);
  console.log(`Wrote ${files} files to public/course-cards/.`);

  mkdirSync(GENERATED_DIR, { recursive: true });
  writeFileSync(join(GENERATED_DIR, 'catalogue.ts'), renderCatalogueModule(catalogue));
  console.log(`Wrote catalogue of ${catalogue.sets.length} sets to lib/course-cards/generated/catalogue.ts.`);
  writeFileSync(join(GENERATED_DIR, 'routing.ts'), renderRoutingModule(version, overlays));
  console.log(`Wrote ${Object.keys(overlays).length} routing overlays to lib/course-cards/generated/routing.ts.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
