/**
 * Sync the course-cards data sets into the app.
 *
 * Run: pnpm course-cards:sync   (also run automatically by `prebuild`)
 *
 * The pinned release lives in lib/course-cards/dataset-version.txt. Two
 * outputs, mirroring scripts/sync-canonical-logos.ts:
 *
 *   - lib/course-cards/generated/catalogue.ts — the committed catalogue of
 *     sets and cards (club, event, card ids, counts), typed as the library
 *     reads it, so the picker renders without a network call.
 *   - public/course-cards/<set>/<file>.json — the marks and card files
 *     themselves, gitignored and re-fetched at build time; the app fetches a
 *     card on demand from its own origin, so there is no CORS and no runtime
 *     dependency on courses.sailscoring.ie.
 *
 * Idempotent: if public/course-cards/.version already matches the pin, the
 * download is skipped so repeat builds are fast and offline-friendly.
 */

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { setTimeout } from 'node:timers/promises';

import { parseCatalogue, parseCourseCardFile, parseMarksFile, type Catalogue } from '@sailscoring/course-cards';

const LIB_DIR = join(__dirname, '..', 'lib', 'course-cards');
const VERSION_FILE = join(LIB_DIR, 'dataset-version.txt');
const GENERATED_DIR = join(LIB_DIR, 'generated');
const PUBLIC_DIR = join(__dirname, '..', 'public', 'course-cards');
const VERSION_MARKER = join(PUBLIC_DIR, '.version');
const SITE = 'https://courses.sailscoring.ie';

const FETCH_ATTEMPTS = 3;
const RETRY_BASE_MS = 1000;

function isRetriableStatus(status: number): boolean {
  return status === 408 || status === 429 || status >= 500;
}

function errorSummary(err: unknown): string {
  if (!(err instanceof Error)) return String(err);
  return err.cause instanceof Error ? `${err.message} (${err.cause.message})` : err.message;
}

/** Fetch one file of the release, retrying the failures worth retrying. */
async function fetchText(url: string): Promise<string> {
  let lastError: unknown;
  for (let attempt = 1; attempt <= FETCH_ATTEMPTS; attempt++) {
    if (attempt > 1) {
      const delay = RETRY_BASE_MS * 2 ** (attempt - 2);
      console.log(`Retrying ${url} in ${delay}ms (attempt ${attempt}/${FETCH_ATTEMPTS}): ${errorSummary(lastError)}`);
      await setTimeout(delay);
    }
    let res: Response;
    try {
      res = await fetch(url);
    } catch (err) {
      lastError = err;
      continue;
    }
    if (res.ok) return res.text();
    const err = new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
    if (!isRetriableStatus(res.status)) throw err;
    lastError = err;
  }
  throw new Error(`Failed to fetch ${url} after ${FETCH_ATTEMPTS} attempts: ${errorSummary(lastError)}`, {
    cause: lastError,
  });
}

function renderCatalogueModule(catalogue: Catalogue): string {
  return [
    '// AUTOGENERATED by scripts/sync-course-cards.ts — do not edit by hand.',
    `// Source: ${SITE}/v${catalogue.version}/index.json`,
    '',
    "import type { Catalogue } from '@sailscoring/course-cards';",
    '',
    `export const COURSE_CARDS_RELEASE = ${JSON.stringify(catalogue.version)};`,
    '',
    `export const COURSE_CARD_CATALOGUE: Catalogue = ${JSON.stringify(catalogue, null, 2)};`,
    '',
  ].join('\n');
}

async function main() {
  const version = readFileSync(VERSION_FILE, 'utf8').trim();
  if (!/^\d+\.\d+\.\d+$/.test(version)) {
    throw new Error(`dataset-version.txt must contain MAJOR.MINOR.PATCH, got ${JSON.stringify(version)}`);
  }

  const haveCatalogue = existsSync(join(GENERATED_DIR, 'catalogue.ts'));
  const haveFiles = existsSync(VERSION_MARKER) && readFileSync(VERSION_MARKER, 'utf8').trim() === version;
  if (haveCatalogue && haveFiles) {
    console.log(`course-cards ${version} already in sync — skipping.`);
    return;
  }

  console.log(`Syncing course-cards ${version}…`);
  const catalogue = parseCatalogue(JSON.parse(await fetchText(`${SITE}/v${version}/index.json`)));
  if (catalogue.version !== version) {
    throw new Error(`catalogue says version ${catalogue.version}, pin says ${version}`);
  }

  rmSync(PUBLIC_DIR, { recursive: true, force: true });
  mkdirSync(PUBLIC_DIR, { recursive: true });
  let files = 0;
  for (const set of catalogue.sets) {
    // Every file is parsed before it is written: a card the library refuses
    // is a release problem to fail the build on, not one to ship.
    const marksText = await fetchText(set.marks.url);
    parseMarksFile(JSON.parse(marksText));
    const marksPath = join(PUBLIC_DIR, set.marks.file);
    mkdirSync(dirname(marksPath), { recursive: true });
    writeFileSync(marksPath, marksText);
    files += 1;
    for (const card of set.cards) {
      const cardText = await fetchText(card.url);
      parseCourseCardFile(JSON.parse(cardText));
      const cardPath = join(PUBLIC_DIR, card.json);
      mkdirSync(dirname(cardPath), { recursive: true });
      writeFileSync(cardPath, cardText);
      files += 1;
    }
  }
  writeFileSync(VERSION_MARKER, `${version}\n`);
  console.log(`Wrote ${files} files to public/course-cards/.`);

  mkdirSync(GENERATED_DIR, { recursive: true });
  writeFileSync(join(GENERATED_DIR, 'catalogue.ts'), renderCatalogueModule(catalogue));
  console.log(`Wrote catalogue of ${catalogue.sets.length} sets to lib/course-cards/generated/catalogue.ts.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
