/**
 * Sync the canonical-logos dataset into the app.
 *
 * Run: pnpm canonical:sync   (also run automatically by `prebuild`)
 *
 * The pinned dataset version lives in lib/canonical-logos/dataset-version.txt.
 * Two outputs:
 *
 *   - lib/canonical-logos/generated/manifest.ts — the committed picker catalogue
 *     (text, diffable, type-checked). Production builds and CI read this without
 *     reaching out to GitHub.
 *   - public/canonical-logos/* — the asset bytes, gitignored and re-fetched at
 *     build time. Keeps large binary churn out of this repo's history (the whole
 *     reason canonical-logos is a separate repo; see
 *     docs/notes/canonical-logo-library.md §2).
 *
 * Idempotent: if public/canonical-logos/.version already matches the pin, the
 * download is skipped so repeat builds are fast and offline-friendly.
 *
 * Trust model: every asset byte is sha256-verified against the value carried in
 * the release manifest.json before it is written.
 */

import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename, join } from 'node:path';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { extract } from 'tar';

const CANONICAL_DIR = join(__dirname, '..', 'lib', 'canonical-logos');
const VERSION_FILE = join(CANONICAL_DIR, 'dataset-version.txt');
const GENERATED_DIR = join(CANONICAL_DIR, 'generated');
const PUBLIC_DIR = join(__dirname, '..', 'public', 'canonical-logos');
const VERSION_MARKER = join(PUBLIC_DIR, '.version');

interface ManifestFile {
  schemaVersion: string;
  logos: ManifestEntry[];
}

interface ManifestEntry {
  id: string;
  class: string;
  displayName: string;
  file: string;
  format: 'svg' | 'png';
  sha256: string;
  quality?: 'ok' | 'provisional';
  derivatives?: { small?: string };
}

function sha256(buf: Buffer): string {
  return createHash('sha256').update(buf).digest('hex');
}

async function fetchAsset(version: string, asset: string): Promise<Buffer> {
  const url = `https://github.com/sailscoring/canonical-logos/releases/download/${version}/${asset}`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  }
  return Buffer.from(await res.arrayBuffer());
}

async function extractTarball(tarball: Buffer): Promise<string> {
  const dir = mkdtempSync(join(tmpdir(), 'canonical-logos-'));
  await pipeline(Readable.from(tarball), extract({ cwd: dir, gzip: true }));
  return dir;
}

function jsonStringEscape(s: string): string {
  return JSON.stringify(s);
}

function renderManifestModule(version: string, entries: ManifestEntry[]): string {
  const lines: string[] = [];
  lines.push('// AUTOGENERATED by scripts/sync-canonical-logos.ts — do not edit by hand.');
  lines.push(`// Source: github.com/sailscoring/canonical-logos @ ${version}`);
  lines.push('');
  lines.push("import type { CanonicalLogo } from '../types';");
  lines.push('');
  lines.push(`export const CANONICAL_DATASET_VERSION = ${jsonStringEscape(version)};`);
  lines.push('');
  lines.push('export const CANONICAL_LOGOS: readonly CanonicalLogo[] = [');
  for (const e of entries) {
    const small = e.derivatives?.small ? basename(e.derivatives.small) : undefined;
    const parts = [
      `id: ${jsonStringEscape(e.id)}`,
      `logoClass: ${jsonStringEscape(e.class)}`,
      `displayName: ${jsonStringEscape(e.displayName)}`,
      `file: ${jsonStringEscape(basename(e.file))}`,
      `format: ${jsonStringEscape(e.format)}`,
      ...(small ? [`small: ${jsonStringEscape(small)}`] : []),
      `quality: ${jsonStringEscape(e.quality ?? 'ok')}`,
    ];
    lines.push(`  { ${parts.join(', ')} },`);
  }
  lines.push('];');
  lines.push('');
  return lines.join('\n');
}

async function main() {
  const version = readFileSync(VERSION_FILE, 'utf8').trim();
  if (!/^v\d+\.\d+\.\d+$/.test(version)) {
    throw new Error(
      `dataset-version.txt must contain a vMAJOR.MINOR.PATCH tag, got ${JSON.stringify(version)}`,
    );
  }

  // When a dedicated origin (logos.sailscoring.ie) serves the assets, the app
  // doesn't bundle them at all — the committed catalogue is enough. Skip the
  // fetch entirely so production builds carry no logo binaries.
  if (process.env.NEXT_PUBLIC_CANONICAL_LOGOS_URL) {
    console.log(
      `canonical-logos served from ${process.env.NEXT_PUBLIC_CANONICAL_LOGOS_URL} — skipping local asset sync.`,
    );
    return;
  }

  // Skip the download when the assets on disk already match the pin. The
  // generated manifest.ts is committed, so it is already present too.
  const haveManifest = existsSync(join(GENERATED_DIR, 'manifest.ts'));
  const haveAssets =
    existsSync(VERSION_MARKER) &&
    readFileSync(VERSION_MARKER, 'utf8').trim() === version;
  if (haveManifest && haveAssets) {
    console.log(`canonical-logos ${version} already in sync — skipping.`);
    return;
  }

  console.log(`Syncing canonical-logos ${version}…`);
  const [manifestBuf, tarballBuf] = await Promise.all([
    fetchAsset(version, 'manifest.json'),
    fetchAsset(version, 'logos.tar.gz'),
  ]);

  const manifest: ManifestFile = JSON.parse(manifestBuf.toString('utf8'));
  if (manifest.schemaVersion !== '1.0') {
    throw new Error(
      `unexpected manifest schemaVersion ${manifest.schemaVersion}; expected 1.0`,
    );
  }

  const tmp = await extractTarball(tarballBuf);
  try {
    rmSync(PUBLIC_DIR, { recursive: true, force: true });
    mkdirSync(PUBLIC_DIR, { recursive: true });

    let verified = 0;
    for (const entry of manifest.logos) {
      const bytes = await readFile(join(tmp, entry.file));
      const actual = sha256(bytes);
      if (actual !== entry.sha256) {
        throw new Error(
          `sha256 mismatch for ${entry.id}: manifest ${entry.sha256}, tarball ${actual}`,
        );
      }
      writeFileSync(join(PUBLIC_DIR, basename(entry.file)), bytes);
      if (entry.derivatives?.small) {
        const small = await readFile(join(tmp, entry.derivatives.small));
        writeFileSync(join(PUBLIC_DIR, basename(entry.derivatives.small)), small);
      }
      verified += 1;
    }
    writeFileSync(VERSION_MARKER, `${version}\n`);
    console.log(`Verified + wrote ${verified} canonical logos to public/canonical-logos/.`);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }

  mkdirSync(GENERATED_DIR, { recursive: true });
  writeFileSync(
    join(GENERATED_DIR, 'manifest.ts'),
    renderManifestModule(version, manifest.logos),
  );
  console.log(`Wrote catalogue of ${manifest.logos.length} entries to lib/canonical-logos/generated/manifest.ts.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
