/**
 * Sync the national-letters dataset into lib/nationality/generated/.
 *
 * Run: pnpm nationality:sync
 *
 * The pinned dataset version lives in lib/nationality/dataset-version.txt.
 * Bump it, run this script, and commit the regenerated codes.ts + flags.ts.
 * Generated files are committed so production builds never reach out to
 * GitHub at build time.
 *
 * Trust model: every flag SVG byte is sha256-verified against the value
 * carried in codes.json (which itself comes from the same release). The
 * dataset's own CI pre-optimises with SVGO, so we don't re-run SVGO here.
 */

import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { readdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { extract } from 'tar';

const NATIONALITY_DIR = join(__dirname, '..', 'lib', 'nationality');
const VERSION_FILE = join(NATIONALITY_DIR, 'dataset-version.txt');
const GENERATED_DIR = join(NATIONALITY_DIR, 'generated');

interface CodesFile {
  schemaVersion: string;
  generatedAt: string;
  codes: CodeEntry[];
}

interface CodeEntry {
  code: string;
  name: string;
  category: string;
  presentIn: string[];
  names: Record<string, string>;
  flag: { file: string; sha256: string };
  iso3166Alpha2: string | null;
  iso3166Alpha3: string | null;
}

interface AliasesFile {
  schemaVersion: string;
  aliases: Record<string, { canonical: string; note?: string; source?: string }>;
}

interface FlagInner {
  /** viewBox attribute value, e.g. "0 0 1200 600". Always present in the dataset's SVGs. */
  viewBox: string;
  /** Markup inside the outer <svg> tag — ready to drop into a <symbol>. */
  inner: string;
}

const SVG_OUTER = /^<svg\b([^>]*)>([\s\S]*)<\/svg>\s*$/;
const VIEWBOX_ATTR = /\bviewBox\s*=\s*"([^"]+)"/;

function parseSvg(code: string, raw: string): FlagInner {
  const match = SVG_OUTER.exec(raw.trim());
  if (!match) {
    throw new Error(`flag SVG for ${code} does not match <svg>…</svg> shape`);
  }
  const viewBoxMatch = VIEWBOX_ATTR.exec(match[1]);
  if (!viewBoxMatch) {
    throw new Error(`flag SVG for ${code} is missing a viewBox attribute`);
  }
  return { viewBox: viewBoxMatch[1], inner: match[2] };
}

function sha256(buf: Buffer): string {
  return createHash('sha256').update(buf).digest('hex');
}

async function fetchAsset(version: string, asset: string): Promise<Buffer> {
  const url = `https://github.com/sailscoring/national-letters/releases/download/${version}/${asset}`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  }
  return Buffer.from(await res.arrayBuffer());
}

async function extractTarball(tarball: Buffer): Promise<Map<string, Buffer>> {
  const dir = mkdtempSync(join(tmpdir(), 'national-letters-'));
  try {
    await pipeline(
      Readable.from(tarball),
      extract({ cwd: dir, gzip: true }),
    );
    const flagsDir = join(dir, 'flags');
    const entries = await readdir(flagsDir);
    const out = new Map<string, Buffer>();
    for (const name of entries) {
      if (!name.endsWith('.svg')) continue;
      out.set(`flags/${name}`, await readFile(join(flagsDir, name)));
    }
    return out;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function jsonStringEscape(s: string): string {
  return JSON.stringify(s);
}

function renderCodesModule(version: string, codes: CodeEntry[], aliases: AliasesFile['aliases']): string {
  const lines: string[] = [];
  lines.push('// AUTOGENERATED by scripts/sync-national-letters.ts — do not edit by hand.');
  lines.push(`// Source: github.com/sailscoring/national-letters @ ${version}`);
  lines.push('');
  lines.push("import type { NationalCode, NationalAlias } from '../types';");
  lines.push('');
  lines.push(`export const DATASET_VERSION = ${jsonStringEscape(version)};`);
  lines.push('');
  lines.push('export const NATIONAL_CODES: readonly NationalCode[] = [');
  for (const c of codes) {
    const parts = [
      `code: ${jsonStringEscape(c.code)}`,
      `name: ${jsonStringEscape(c.name)}`,
      `iso3166Alpha2: ${c.iso3166Alpha2 == null ? 'null' : jsonStringEscape(c.iso3166Alpha2)}`,
      `iso3166Alpha3: ${c.iso3166Alpha3 == null ? 'null' : jsonStringEscape(c.iso3166Alpha3)}`,
    ];
    lines.push(`  { ${parts.join(', ')} },`);
  }
  lines.push('];');
  lines.push('');
  lines.push('export const NATIONAL_ALIASES: Readonly<Record<string, NationalAlias>> = {');
  for (const [from, { canonical, note }] of Object.entries(aliases)) {
    const parts = [
      `canonical: ${jsonStringEscape(canonical)}`,
      ...(note ? [`note: ${jsonStringEscape(note)}`] : []),
    ];
    lines.push(`  ${jsonStringEscape(from)}: { ${parts.join(', ')} },`);
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

function renderFlagsModule(version: string, codes: CodeEntry[], flagInners: Map<string, FlagInner>): string {
  const lines: string[] = [];
  lines.push('// AUTOGENERATED by scripts/sync-national-letters.ts — do not edit by hand.');
  lines.push(`// Source: github.com/sailscoring/national-letters @ ${version}`);
  lines.push('//');
  lines.push('// This module embeds every flag SVG inline. Importing it pulls the full');
  lines.push('// dataset into the bundle — keep this server-only or behind dynamic imports.');
  lines.push('');
  lines.push("import type { NationalFlag } from '../types';");
  lines.push('');
  lines.push('export const NATIONAL_FLAGS: Readonly<Record<string, NationalFlag>> = {');
  for (const c of codes) {
    const flag = flagInners.get(c.flag.file);
    if (!flag) throw new Error(`flag missing from tarball for ${c.code}`);
    lines.push(
      `  ${jsonStringEscape(c.code)}: { viewBox: ${jsonStringEscape(flag.viewBox)}, inner: ${jsonStringEscape(flag.inner)} },`,
    );
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

async function main() {
  const version = readFileSync(VERSION_FILE, 'utf8').trim();
  if (!/^v\d+\.\d+\.\d+$/.test(version)) {
    throw new Error(`dataset-version.txt must contain a vMAJOR.MINOR.PATCH tag, got ${JSON.stringify(version)}`);
  }
  console.log(`Syncing national-letters ${version}…`);

  const [codesBuf, aliasesBuf, tarballBuf] = await Promise.all([
    fetchAsset(version, 'codes.json'),
    fetchAsset(version, 'aliases.json'),
    fetchAsset(version, 'flags.tar.gz'),
  ]);

  const codes: CodesFile = JSON.parse(codesBuf.toString('utf8'));
  const aliases: AliasesFile = JSON.parse(aliasesBuf.toString('utf8'));

  if (codes.schemaVersion !== '1.0') {
    throw new Error(`unexpected codes.json schemaVersion ${codes.schemaVersion}; expected 1.0`);
  }
  if (aliases.schemaVersion !== '1.0') {
    throw new Error(`unexpected aliases.json schemaVersion ${aliases.schemaVersion}; expected 1.0`);
  }

  const flagBytes = await extractTarball(tarballBuf);

  const flagInners = new Map<string, FlagInner>();
  let verified = 0;
  for (const c of codes.codes) {
    const bytes = flagBytes.get(c.flag.file);
    if (!bytes) throw new Error(`flag ${c.flag.file} missing from flags.tar.gz`);
    const actual = sha256(bytes);
    if (actual !== c.flag.sha256) {
      throw new Error(
        `sha256 mismatch for ${c.code}: codes.json says ${c.flag.sha256}, tarball has ${actual}`,
      );
    }
    flagInners.set(c.flag.file, parseSvg(c.code, bytes.toString('utf8')));
    verified += 1;
  }
  console.log(`Verified ${verified} flag SVGs against codes.json sha256 hashes.`);

  writeFileSync(join(GENERATED_DIR, 'codes.ts'), renderCodesModule(version, codes.codes, aliases.aliases));
  writeFileSync(join(GENERATED_DIR, 'flags.ts'), renderFlagsModule(version, codes.codes, flagInners));
  console.log(`Wrote ${codes.codes.length} codes + flags to lib/nationality/generated/.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
